---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-metrics
rules:
  # Rule 1: Resource-based permissions (nodes, proxy for kubelet/cAdvisor, discovery)
  - apiGroups: [""]
    resources: ["nodes", "nodes/stats", "nodes/proxy"]
    verbs: ["get", "list", "watch"]

  # Rule 2: Separate rule for any direct non-resource URLs
  - nonResourceURLs:
      - "/metrics"
      - "/metrics/*"
    verbs: ["get"]

  # Rule 3: Discovery for kubernetes_sd_configs (pods, services, endpoints, nodes)
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]

  # Optional: Extra for richer labels (deployments etc.)
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-metrics-binding
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: otel-collector-metrics
  apiGroup: rbac.authorization.k8s.io