{
 "title": "RiddleBuddy6",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of replicas available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"riddlebuddy-(api|feedback)\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "stat",
   "description": "Check request success rate ",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{status!~\"5..\"}[5m]))\r\n  /\r\n  sum(rate(http_requests_total[5m]))\r\n) OR vector(0)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "Is my service failing ?",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))\r\n  /\r\n  sum(rate(http_server_requests_seconds_count[1m])) * 100\r\n) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{k8s_namespace_name=\"riddlebuddy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{k8s_namespace_name=\"riddlebuddy\"}[5m])) by (service_name, path)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{k8s_namespace_name=\"riddlebuddy\"}[5m])\r\n/\r\nrate(http_request_duration_seconds_count{k8s_namespace_name=\"riddlebuddy\"}[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_requests_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "Feedback Service (Java)"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "RiddleBuddy API (FastAPI)"
    }
   ]
  },
  {
   "title": "Traffic Per Service",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[5m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Infrastructure & Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", container!=\"POD\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(container_cpu_usage_seconds_total{id=\"/\", container=\"\", mode!=\"idle\"}[5m])) by (instance)\r\n/\r\nsum(machine_cpu_cores) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"riddlebuddy\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"riddlebuddy\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deepseek API call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "DeepSeek call success rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(deepseek_requests_total{status=\"success\"})/sum(deepseek_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 2, "x": 3, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(deepseek_requests_total{status!=\"success\"}[5m])) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(increase(deepseek_latency_seconds_bucket[10m])) by (le)\r\n)",
     "legendFormat": "DeepSeek P95"
    }
   ]
  }
 ]
}