{
 "title": "TestDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "General logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"riddlebuddy-api\"}"
    },
    {
     "direction": "backward",
     "expr": "{app=\"riddlebuddy-feedback\"}"
    }
   ]
  },
  {
   "title": "Error log rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"riddlebuddy-api\"} |= \"ERROR\" [5m]) OR vector(0)",
     "legendFormat": "api"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"riddlebuddy-feedback\"} |= \"ERROR\" [5m]) OR vector(0)",
     "legendFormat": "feedback"
    }
   ]
  },
  { "title": "Service health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of replicas available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"riddlebuddy-(api|feedback)\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{status!~\"5..\"}[5m]))\r\n  /\r\n  sum(rate(http_requests_total[5m]))\r\n) OR vector(0)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "Is my service failing ?",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))\r\n  /\r\n  sum(rate(http_server_requests_seconds_count[1m])) * 100\r\n) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{namespace=\"riddlebuddy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic & Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[10m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[5m])\r\n/\r\nrate(http_server_requests_seconds_count[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_requests_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "Feedback Service (Java)"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "RiddleBuddy API (FastAPI)"
    }
   ]
  },
  {
   "title": "Traffic Per Service",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 10, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[5m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infrastructure & Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node memory usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 8, "y": 99 },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage by pod",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"riddlebuddy\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"riddlebuddy\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Deepseek API call",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "DeepSeek call success rate",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(deepseek_requests_total{status=\"success\"})/sum(deepseek_requests_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failure count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 2, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(deepseek_requests_total{status!=\"success\"}[5m])) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(increase(deepseek_latency_seconds_bucket[10m])) by (le)\r\n)",
       "legendFormat": "DeepSeek P95"
      }
     ]
    }
   ]
  }
 ]
}